#ifndef RUFALU_TESTS_POLYA_HPP
#define RUFALU_TESTS_POLYA_HPP

#include <string>

#include "polyATail.h"

TEST(PolyATests, TruePolyA){
  std::string contig = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATCAGGAGGCACAAAATATCGGTGCATCTCATTGTTGTGATGCCAAGTTTGATCACTTAAGGCAATATTGACTAGATTTCTCCATCATAA";
  ASSERT_TRUE(polyA::detectPolyATail(contig));

}

TEST(PolyATests, FalsePolyA){
  std::string contig = "AAAAAAACAAAAAAAAAAACAAAAAAAAACAAAAAAAAAACAAAAAAAAAAACAAAAAAAACAAAAAATCAGGAGGCACAAAATATCGGTGCATCTCATTGTTGTGATGCCAAGTTTGATCACTTAAGGCAATATTGACTAGATTTCTCCATCATAA";
  ASSERT_FALSE(polyA::detectPolyATail(contig));
}

TEST(PolyATests, TruePolyT){
  std::string contig = "AGATGCACCGATATTTTGTGCCTCCTGATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGGTTTTTTTTTTTTTTTTTTTTTTGTTGTTTGTTTTTTTTTTTGTTTGTTTTCTT";
  ASSERT_TRUE(polyA::detectPolyTTail(contig));

}

TEST(PolyATests, FalsePolyT){
  std::string contig = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATCAGGAGGCACAAAATATCGGTGCATCTCATTGTTGTGATGCCAAGTTTGATCACTTAAGGCAATATTGACTAGATTTCTCCATCATAA";
  ASSERT_FALSE(polyA::detectPolyTTail(contig));
}

#endif //RUFALU_TESTS_POLYA_HPP
